            # Array manipulation routines

In [15]:
import numpy as np

In [16]:
np.__version__

'2.0.0rc2'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [17]:
x = np.ones([10, 10, 3])
print(x.shape)
x = np.reshape(x, [2, 150])
print(x)

(10, 10, 3)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [18]:

x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.transpose(x)
x = np.reshape(x, (1, 6))
print(x)
# x = x.flatten()
# print(x)

[[1 4 2 5 3 6]]


Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [19]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.array([[1, 2, 3], [4, 5, 6]])
x = np.transpose(x)
x = x.flatten()
print(x[5])

6


Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [20]:
x = np.ones((3, 4, 5))
x = np.transpose(x, (1, 0, 2))
x.shape

(4, 3, 5)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [21]:
x = np.ones((3, 4))
x = np.swapaxes(x, 1, 0)

x.shape


(4, 3)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [22]:
x = np.ones((3, 4))
x = x[:, np.newaxis, :]

x.shape


(3, 1, 4)

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [23]:
x = np.ones((3, 1, 4))
x = np.squeeze(x, 1)
x.shape

(3, 4)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [24]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.concatenate((x, y), axis=1)
print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [25]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.concatenate((x, y), axis=0)
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [26]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.concatenate([(x, y)], axis=1)
z = np.transpose(z)

print(z)

[[1 4]
 [2 5]
 [3 6]]


Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [27]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [37]:
x = np.arange(1, 10)
indices = [4, 6]
print(np.array_split(x, indices))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [47]:
x = np.array([[[0., 1., 2., 3.], [4., 5., 6., 7.]],
              [[8., 9., 10., 11.], [12., 13., 14., 15.]]])

x1 = x[:, :, :3]
x2 = x[:, :, 3:]
print(x1)
print(x2)

[[[ 0.  1.  2.]
  [ 4.  5.  6.]]

 [[ 8.  9. 10.]
  [12. 13. 14.]]]
[[[ 3.]
  [ 7.]]

 [[11.]
  [15.]]]


Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [50]:
x = np.array([[0., 1., 2., 3.], [4., 5., 6., 7.], [8., 9., 10., 11.], [12., 13., 14., 15.]])
x = np.split(x, 2, axis=1)
x

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [51]:
x = np.array([[0., 1., 2., 3.], [4., 5., 6., 7.], [8., 9., 10., 11.], [12., 13., 14., 15.]])
x = np.split(x, 2, axis=0)
x

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [98]:
x = np.array([0, 1, 2])
for i in range(3):
    x = np.array(np.append(x, [0, 1, 2]))
x = x.reshape((2, 6))
print(x)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [103]:
x = np.array([0, 1, 2])
x = np.append(x, x)
np.sort(x)


array([0, 0, 1, 1, 2, 2])

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [106]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

x = np.trim_zeros(x)
x

array([1, 2, 3, 0, 2, 1])

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [109]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
unique_elements, counts = np.unique(x, return_counts=True)
print(unique_elements)
print(counts)

[1 2 3 4 5]
[2 3 1 1 2]


Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [111]:
x = np.array([[1, 2], [3, 4]])
x = np.flip(x,axis=1)
x

array([[2, 1],
       [4, 3]])

Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [112]:
x = np.array([[1, 2], [3, 4]])
x = np.flip(x,axis=0)
x

array([[3, 4],
       [1, 2]])

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [116]:
x = np.array([[1, 2], [3, 4]])

# Rotate 90 degrees counter-clockwise
rotated_x = np.rot90(x)
print(rotated_x)

[[2 4]
 [1 3]]


Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [119]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Shift elements one step to the right along the second axis
shifted_x = np.hstack((x[:, -1:], x[:, :-1]))
print(shifted_x)

[[4 1 2 3]
 [8 5 6 7]]
